### ISSUE TITLE
Failed to add edges to graph of Char vertices

### ISSUE THREAD

**Issue by yitapi** [JuliaLang/Graphs.jl#120] opened 2014-09-03 04:00 UTC
Here's what I did:
     
    julia> g = graph(Char[], Edge{Char}[])
    Directed Graph (0 vertices, 0 edges)

    julia> add_vertex!(g, 'a')
    'a'

    julia> add_vertex!(g, 'b')
    'b'

    julia> add_edge!(g, 'a', 'b')
    ERROR: type: add_edge!: in typeassert, expected Int64, got Char
     in add_edge! at /home/filius/.julia/Graphs/src/graph.jl:82
     in add_edge! at /home/filius/.julia/Graphs/src/graph.jl:98

Is there something wrong with what I did here, or with `vertex_index` (which return Char as the index instead of Int64) ?

**Comment by sbromberger** [comment] 2015-01-13 03:19
@yitapi - I believe this is fixed now. I can't reproduce this in the latest version on either 0.3 or 0.4.

@erickhsiao - the issue is that you're trying to add an `ASCIIString` vertex ("a") to a graph that requires `Char` vertices ('a'). If you put single quotes instead of double quotes, you should be ok.

**Closed** 2016-01-27 14:00 UTC
